name: sakin_app
description: A pure offline Prayer & Habit tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Design
  package_info_plus: ^8.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.20.0
  hijri: ^3.0.0
  timezone: ^0.9.2 # For local notification scheduling
  provider: ^6.1.1

  # Data & Engine
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  adhan: ^2.0.0
  
  # Background & Notifications
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1 # For permission assistance
  just_audio: ^0.9.36 # For playing Adhan
  geolocator: ^13.0.4 # For user location
  geocoding: ^3.0.0 # To get city name from coordinates
  android_alarm_manager_plus: ^4.0.4 # For accurate Adhan scheduling
  flutter_qiblah: ^3.1.0 # For Qibla direction
  wakelock_plus: ^1.3.3
  android_intent_plus: ^6.0.0
  flutter_foreground_task: ^9.2.0
  hugeicons: ^1.1.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  bloc: ^9.2.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_test: ^1.0.1
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF" # or #000000
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
